# Site settings
title: Omega Alumini Association
email: admin@omegacollege.edu.np
description: "This site provides a basic information about Omega Alumini Association their aims and activities."
baseurl: ""
url: "http://alumini.omegacollege.edu.np"
twitter_username: frensOfAll
github_username:  shubhajeet

# Build settings
markdown: kramdown
permalink: pretty
