# Site settings
title: Omega Alumini Association

description: "This site provides a basic information about Omega Alumini Association their aims and activities."
baseurl: "/alumini"
url: "http://alumini.omegacollege.edu.np"

org:
  twitter: frensOfAll
  facebook:
  email: admin@omegacollege.edu.np
  address:
    lat:
    long:
    place: Kumaripati

# Build settings
markdown: kramdown
permalink: pretty

collections:
  events:
    output: true
    premalink: /events/:path/
    layout: notice
  links:
    output: true
    pemalink: /:path/

# Paginate
paginate: 5
paginate_path: 'Notice/page:num/'
