# Site settings
title: Omega Alumini Association

description: "This site provides a basic information about Omega Alumini Association their aims and activities."
baseurl:
url: "http://alumni.omegacollege.edu.np"

org:
  twitter: frensOfAll
  facebook:
  email: admin@omegacollege.edu.np
  address:
    lat:
    long:
    place: Kumaripati

# Build settings
markdown: kramdown
permalink: pretty

collections:
  events:
    output: true
    premalink: /events/:path/
    layout: notice
  links:
    output: true
    pemalink: /:path/

# Paginate
paginate: 5
paginate_path: 'Notice/page:num/'

# Prose
prose:
  # rooturl: ['_post','_data','_events']
  siteurl: "https://alumni.omegacollege.edu.np"
  media: "images"
  metadata:
    _posts:
      - name: "layout"
        field:
          value: "post"
