# Site settings
title: Omega Alumini Association

description: "This site provides a basic information about Omega Alumini Association their aims and activities."
baseurl:
url: "http://alumni.omegacollege.edu.np"

org:
  facebook:
    group: https://www.facebook.com/groups/alumniomega/
    page: https://www.facebook.com/OmegaAlumni
  email: alumni@omegacollege.edu.np
  address:
    lat:
    long:
    place: Kumaripati

# Build settings
markdown: kramdown
permalink: pretty

collections:
  events:
    output: true
    premalink: /events/:path/
    layout: notice
  links:
    output: true
    pemalink: /:path/
  forms:
    output: true
    pemalink: /forms/:path/

# Paginate
paginate: 5
paginate_path: 'NewsNotices/page:num/'

# Prose
prose:
  siteurl: "https://alumni.omegacollege.edu.np"
  media: "images"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          value: "post"
